### PR TITLE
`flutter pub upgrade --major-versions`

### PR DESCRIPTION
**Pull request by domesticmouse**
## Description

Updating dependencies

## Type of Change

- [ ] ✨ New feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking change (fix or feature that would cause existing functionality to change)
- [ ] 🧹 Code refactor
- [ ] ✅ Build configuration change
- [ ] 📝 Documentation
- [x] 🗑️ Chore

### CODE REVIEW

**Comment by felangel** [comment]
Thanks for the PR! Looks like the tests are failing. Let me know if you need help getting the ci to pass.

**Comment by domesticmouse** [comment]
> Thanks for the PR! Looks like the tests are failing. Let me know if you need help getting the ci to pass.

The tests are failing because the tests are pinned to run against Flutter 2.8.0, but this code has been updated to run correctly on Flutter 2.10.x. The tests are never going to pass until the test Flutter version unpin included in this PR is landed.

**Comment by felangel** [comment]
> > Thanks for the PR! Looks like the tests are failing. Let me know if you need help getting the ci to pass.
> 
> The tests are failing because the tests are pinned to run against Flutter 2.8.0, but this code has been updated to run correctly on Flutter 2.10.x. The tests are never going to pass until the test Flutter version unpin included in this PR is landed.

I think https://github.com/VGVentures/slide_puzzle/pull/17/commits/9add10626a2db63ae37c99c81b289f6c687572fb should resolve the issue. We just needed to also update the PR workflow in addition to the deploy workflow.

**Review by felangel — APPROVED** [review]

**Comment by domesticmouse** [comment]
Please feel free to land at your convenience =)

**Pull request merged**
